---
- name: Test debugging
  hosts: "{{ run_environment }}"
  gather_facts: false
  become: false

  tasks:

    - name: Run role in collection
      ansible.builtin.include_role:
        name: zilux.groupsvars.debugging
      # vars:
      #  debugging_motd: Just a message
